gnome-settings-daemon/org.gnome.ScreenSaver.xml
plugins/power/gsd-power-manager.c

Previously blanking was only done if screensaver was not on the screen
yet but we need this functionality fixed for lock screen events.
[endlessm/eos-shell#1532]

Shell: Allow blanking the screen even if screensaver is up

---

plugins/keyboard/gsd-keyboard-manager.c

This ensures we have at least a layout that can be used to type ASCII
characters.
We do not add it for new users as they can add new layouts at any time.
[endlessm/eos-shell#3364]

Add en_US layout in GDM

---

plugins/power/Makefile.am
plugins/power/gsd-power-manager.c
plugins/power/led-breathe.c

For the Endless EC-200, ask the LED to breathe when the display is powered
down, and return it to solid-on when the display is turned on again.
[endlessm/eos-shell#4554]

Control breathing LED on EC-200

---

plugins/power/gsd-power-constants.h

Upon waking from a screen lock, if the user stops typing,
the password screen is only displayed for 15 seconds.
This can be a bit confusing to users, especially if using
an external display that takes several seconds to wake up.
Let's bump this timeout up to 30 seconds.
[endlessm/eos-shell#5212]

Increase blank delay for screensaver

---

plugins/mouse/gsd-mouse-manager.c

If the user disables the touchpad using the touchpad toggle hotkey we
should honor it instead of re-enabling the touchpad, even if there is
no other type of pointing device present in the system.
Without this patch the situation when using the touchpad toggle hotkey
is as follows:
* 1st press: OSD "touchpad disabled" shows up, cursor movement is disabled,
but the touchpad settings are still available under "Mouse & Touchpad" in
g-c-c.
* 2nd press: OSD "touchpad disabled" shows up, cursor movement remains
disabled, and now the touchpad settings are greyed out under "Mouse &
Touchpad" in g-c-c.
* 3rd press: OSD "touchpad enabled" shows up, cursor movement is re-enabled
and touchpad settings are available again under "Mouse & Touchpad" in g-c-c,
but a new ON|OFF switch is created in the …

mouse: Do not re-enable touchpad on touchpad disable

---

plugins/power/led-breathe.c

Add support for the breathing LED control on EC-100, which is
controlled by GPIOAO_7.
[endlessm/eos-shell#5562]

led-breathe: add EC-100 support

---

plugins/xsettings/gsd-xsettings-manager.c

If the eos-composite-mode package is installed, the com.endlessm.CompositeMode
will be available to provide an additional, accumulative, scaling factor to be
used on top of the one from org.gnome.desktop.interface, so we need to check
it here to determine the right value to set for the global Xft DPI setting.
[endlessm/eos-shell#6197]

Consider com.endlessm.CompositeMode.text-scaling-factor GSetting if available

---

configure.ac
plugins/keyboard/Makefile.am
plugins/keyboard/gsd-keyboard-manager.c
plugins/keyboard/gsd-xkb-utils.c
plugins/keyboard/gsd-xkb-utils.h
plugins/keyboard/test-keyboard-ibus-utils.c

GnomeXkbInfo needs to drop its X dependency to be used on a wayland
compositor gnome-shell and in that case the xkb data path is an
implementation detail.
This g-s-d plugin will still be used on X only setups so we'll move
the code here.
https://bugzilla.gnome.org/show_bug.cgi?id=724277

keyboard: Move code to get the XkbRF_VarDefsRec here

---

plugins/media-keys/shortcuts-list.h

The HP Stream 11 Pro G2 has a media key labeled with a question mark
('?') on F1, which sends a combination of LEFT_META and F1. On Windows
it opens the an UI that says "Getting started", so mapping it to open
the Help Center is a sensible solution.
https://phabricator.endlessm.com/T10958

media-keys: Map LEFT_META+F1 to Help by default

---

plugins/media-keys/shortcuts-list.h

This is what Windows hardcodes, and some laptops have keyboards with
"help" physical keys that send Super+F1 when pressed.
https://phabricator.endlessm.com/T10958

media-keys: add Super+F1 as a hardcoded shortcut for launching Help

---

plugins/mouse/gsd-mouse-manager.c

After the change to use "Synaptics Off" instead of "Device Disable" it
is not possible to disable the touchpad in systems which the
KEY_TOUCHPAD_TOGGLE event arrives through the keyboard input device,
because syndaemon reverts it back to 0.
This is the sequence of changes I see on a Yoga 900 running g-s-d
3.18.3 when I press the touchpad toggle key (on F6):
- "Synaptics Off" changes to 2, because the function key press is
considered typing by syndaemon;
- The touchpad settings panel ON|OFF switch changes to OFF, and
"Synaptics Off" changes to 1, to react to the KEY_F21 (touchpad
toggle) event sent through the input device;
- "Synaptics Off" changes to 0, because 1 second has passed since the
last keystroke. The touchpad settings panel ON|OFF switch does not
change back to ON.
- On a 2nd …

mouse: Change "disable while typing" before state

---

plugins/media-keys/gsd-media-keys-manager.c

On the Lenovo Yoga 900 a touchpad-toggle event is generated when the lid
is closed, so when the lid is re-opened the touchpad enable state is
reversed. Ignoring a touchpad-toggle event when the lid is closed avoids
this behavior.
https://phabricator.endlessm.com/T11500

T11500: Ignore touchpad-toggle if lid is closed

---

plugins/media-keys/gsd-media-keys-manager.c

Ignoring the touchpad-toggle key event for 2s has helped, but the
problem still occurs ocasionally. Let's increase the timeout for 5s.
https://phabricator.endlessm.com/T11500

media-keys: Increase the touchpad-toggle ignore timer

---

plugins/xsettings/fontconfig-monitor.c

Currently, the fontconfig monitor will call FcInitReinitialize() for
every event triggered by the file monitor on the fontconfig
configuration directories.
For large font files this creates a situation where the configuration is
reinitialized before the file has been fully copied and available for
use in fontconfig. The result is that the cache mtime for that directory
will be updated to use the current modification time, with the new font
file not registered in the cache yet, preventing the new font to be
avaialble to applications until the fontconfig cache is forcefully
recreated.
We can fix this by ignoring CREATED and CHANGED events from the file
monitor; in both those cases we will receive a CHANGES_DONE_HINT event
when the file is completely copied in the directory. …

fontconfig-monitor: do not recreate configuration every event

---

plugins/print-notifications/gsd-print-notifications-manager.c

This is an attempt to reduce the 'chatty-ness' of desktop notifications when
joining a network with publicly shared printers that get automatically added.
https://phabricator.endlessm.com/T19323

Also consider 'Discovered' printers as remote printers for notifications

---

plugins/print-notifications/gsd-print-notifications-manager.c

This turned out not to be the right fix, the problem was that we had a too
old version of cups-browsed that was causing that CUPS did not set the
CUPS_PRINTER_REMOTE flag for the discovered printers. Upgrading to a
newer version of cups-filters fixed the problem.
This reverts commit 9b698b83a39e2c00016951b02dad23a47da7aa48.
https://phabricator.endlessm.com/T19323

Revert "Also consider 'Discovered' printers as remote printers for notifications"

---

plugins/media-keys/shortcuts-list.h

This reverts commit 858346b784ee986ef536b68827959105fea84460.
On some Acer Aspire laptops (ES1-432, E5-575, E5-523G, A315-21) this
change breaks the airplane-mode media key, as the RFKill input handler
does not work there.
We will investigate the problem in rfkill-input, but for now lets revert
this commit to avoid user-visible regressions.
https://phabricator.endlessm.com/T19631

Revert "media-keys: Disable rfkill keys handling"

---

plugins/color/gsd-night-light.c
plugins/datetime/gsd-timezone-monitor.c

This will prevent using geoclue when Location is disabled in the global settings.
https://phabricator.endlessm.com/T19494

Honor location settings from color and datetime panels

---

plugins/keyboard/gsd-keyboard-manager.c

We no longer need this as we now have an ibus Flatpak portal that is the
appropriate way to fix this.
This reverts commit a8be5ac9f8de6529badf79becffb4063d6e0f48d.
https://phabricator.endlessm.com/T19709

Revert "Set the gtk-im-module setting as 'xim' for IBus input methods"

---

configure.ac
plugins/power/Makefile.am
plugins/power/gpm-common.c

Linux generally use sysfs for backlight control, but this is not
true for the proprietary nvidia driver, where the only known backlight
control interface is through xrandr.
gnome-settings-daemon already has the right codepath here, but it is
only activated on non-Linux. Activate it for the nvidia driver instead.
This patch can be dropped in future, when the nvidia driver migrates
to offering backlight control in /sys (also needed for wayland).
https://phabricator.endlessm.com/T19517

power: Use xrandr backlight control for nvidia driver

---

plugins/power/gsd-power-manager.c

https://phabricator.endlessm.com/T19702

power: Do not compute percentage on keyboard disappearing

---

plugins/media-keys/shortcuts-list.h
plugins/rfkill/gsd-rfkill-manager.c
plugins/rfkill/rfkill-glib.c
plugins/rfkill/rfkill-glib.h

This series adds support the the XF86RFKill keysym and inhibits the rfkill-input kernel handlers to avoid conflicts with userspace handling of KEY_RFKILL.
https://phabricator.endlessm.com/T20508

Handle XF86RFKill

---

data/org.gnome.settings-daemon.plugins.power.gschema.xml.in.in

According to the EU Commission Regulation No 801/2013, amending
Regulation (EC) No 1275/2008:
"
The default period of time after which the power management function,
or a similar function, switches the equipment automatically into a
condition providing networked standby shall not exceed 20 minutes.
"
(Full text at:
http://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32013R0801&from=EN )
Though this addition only seems to be applicable to "networked
equipment", the original directive and its 2008 "ecodesign" regulation
mentions that computers are covered (as "Information technology equipment intended
primarily for use in the domestic environment"), and that:
"
When equipment is not providing the main function, or when other energy-using
product(s) are not dependent on its …

power: Default to suspend after 20 minutes of inactivity

---

.gitmodules
plugins/power/gpm-common.c

The user could slide the brightness on the control panel or press the
function key to make the screen brightness to 0.
However, If the user does not know about the keyboard buttons, he/she
will have a hard time turning the display back from the control panel if
the display is too dim or completely off.
For example, systems like ASUS UX550GE's brightness is in the range from
1 to 120000.  The brightness level 1 has the backlight level which is so
dim and it's also practically unusable.
This patch makes it limiting to 1% brightness as the lower bound avoids
that usability issue.
Signed-off-by: Jian-Hong Pan <jian-hong@endlessm.com>
(cherry picked from commit 1538fd045ac88e5916bdc32f60331331b744a39e)
Signed-off-by: Robert McQueen <rob@endlessm.com>
https://phabricator.endlessm.com/T4839

gsd: Control panel and function key should not set brightness to 0

---

plugins/a11y-keyboard/gsd-a11y-keyboard-manager.c
plugins/color/gsd-color-calibrate.c
plugins/datetime/gsd-datetime-manager.c
plugins/housekeeping/gsd-disk-space.c
plugins/power/gsd-power-manager.c
plugins/print-notifications/gsd-print-notifications-manager.c
plugins/print-notifications/gsd-printer.c

This allows the notifications to be tied back to an application (or, in
this case, control panel capplet) which is related to it; and allows the
user to specify per-app preferences for how the notifications are to be
displayed.
(Backport to EOS: Fix merge conflicts in plugins/print-notifications;
support additional notification in plugins/a11y-keyboard.)
https://wiki.gnome.org/Initiatives/GnomeGoals/NotificationSource
Signed-off-by: Philip Withnall <withnall@endlessm.com>
https://phabricator.endlessm.com/T20990

plugins: Add desktop-entry hints to notifications

---

plugins/media-keys/shortcuts-list.h

Some budget laptops send Ctrl + Super + custom-scancode when their
touchpad-toggle hotkey (Fn + something) gets pressed.
hwdb will map the custom-scancode to TouchpadToggle, but we need to deal
with the Ctrl + Super in the media-keys plugin, add a mapping for this.
https://bugzilla.gnome.org/show_bug.cgi?id=793610

media-keys: Add mapping for Ctrl + Super + TouchpadToggle

---

plugins/power/gsd-power-manager.c

When try to suspend system by GUI or terminal on the laptops like ASUS
E402YA, system blanks screen, but then also flashes the locked screen
for a second. According to the gdb log, we noticed the
backlight_disable() is invoked twice for suspending.
Thread 1 "gsd-power" hit Breakpoint 1, backlight_disable (manager=manager@entry=0x560dda4a0150)
at ../plugins/power/gsd-power-manager.c:1055
1055	../plugins/power/gsd-power-manager.c: No such file or directory.
(gdb) bt
#0  backlight_disable (manager=manager@entry=0x560dda4a0150) at ../plugins/power/gsd-power-manager.c:1055
#1  0x0000560dd84d9f1c in handle_suspend_actions (manager=0x560dda4a0150) at ../plugins/power/gsd-power-manager.c:2412
#2  logind_proxy_signal_cb (proxy=<optimized out>, sender_name=<optimized out>, …

power: lock screen in handle_suspend_actions

---

plugins/media-keys/gsd-media-keys-manager.c

Since the OSD in the shell changed [1] to using float values from 0.0 to
1.0, send a double instead of a percentage via DBus.
[1] https://gitlab.gnome.org/GNOME/gnome-shell/merge_requests/385
https://phabricator.endlessm.com/T28848

media-keys: Divide keyboard brightness value by 100

---

debian/changelog

Signed-off-by: Philip Withnall <withnall@endlessm.com>
https://phabricator.endlessm.com/T28835
---
Code changes in #67. **This should be pushed via the command line rather than GitHub.**

debian: Bump version to 3.36.0-0endless1

---

plugins/xsettings/gsd-xsettings-manager.c

This reverts commit 1f46f948f5b4c00666446b785faaf62429a05f0a temporarily
until we do the full Mutter rebase.

Preparations for 3.37 / 3.9
